Dockerfile
README.md
Testing/CMake/ConfiguredAppLauncher-ConfigurationContents.cmake
Testing/Docker/Dockerfile
circle.yml
docker-build-package.sh

This pull request adds support for building, packaging, and testing the AppLauncher on Linux. This has multiple advantages.
- The package is built on an old version of CentOS, which has a glibc version that makes the binaries generated compatible with most Linux distributions.
- The CentOS Docker build image also has a newer version of the compiler, which generates better optimized binaries.
- The build steps are explicit and reproducible.
- The test suite can be automatically run on pull requests.
- A new package is automatically generate and is easily accessible after every merge.
This topic branch
- Adds a Dockerfile to build and package the repository.
- Adds a Dockerfile for an image with graphical support to run the test suite.
- Fixes the test suite to be compatible with the latest …

Docker support.

---

circle.yml

The use of 'docker cp' in the tests on CircleCI recently failed with
permission denied errors.  This was due to a LXC security upgrade on CircleCI.
The workaround is to use a patched version of Docker.
See:
https://discuss.circleci.com/t/unable-to-use-docker-cp-but-it-worked-2-days-ago/1137/6

Workaround current 'docker cp' permission denied issue on CircleCI.

---

CMakeLists.txt

This commit adds support to exclude use of -fvisibility=hidden and
-fvisibility-inlines-hidden flags.
This allows to address "different visibility" warnings reported in [1]
[1] https://github.com/Slicer/Slicer/pull/727#issuecomment-303908680

Add option CTKAppLauncher_VISIBILITY_HIDDEN

---

CMake/CTKAppLauncherLibConfig.cmake.in

Since on MacOSX not all modules are available as "framework" (e.g libQtUiTools.a),
the assumption made in "FindQt4.cmake" is not always valid and systematically
setting QT_USE_IMPORTED_TARGETS to 1 will cause build error.
Indeed, it turns out that FindQt4.cmake expects all libraries to be
available as framework if at least "QtCore.framework" is available but this
is not true for QtUiTools.

CTKAppLauncherLibConfig: Do not force use of Qt4 imported targets

---

Base/ctkAppLauncher.cpp
Base/ctkAppLauncherEnvironment.cpp
Base/ctkAppLauncherSettings.cpp

This PR fixes some C4996 deprecation warnings.
cc: @jcfr 
```
warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
warning C4996: 'QList<QString>::toSet': Use QSet<T>(list.begin(), list.end()) instead.
warning C4996: 'QString::SkipEmptyParts': was declared deprecated
warning C4996: 'QString::split': Use Qt::SplitBehavior variant instead
warning C4996: 'QSet<T>::toList': Use values() instead.
```

COMP: Fix deprecation warning C4996

---

Base/ctkAppLauncherEnvironment.cpp

Fixes #116
Each call to `ctkAppLauncherEnvironment::excludeReservedVariableNames` returns a new `QStringList` so making a QSet from the `begin()` of one and the `end()` of the other led to the crash in the `QHash`.
Solution is to make temporary variables for the `QStringList`s so that the set is made from matching iterators variables.
Also rearranged the code a bit for readability.

BUG: fix crash calculating environment keys

---

Base/ctkAppLauncher.cpp
Base/ctkAppLauncher.h
Base/ctkAppLauncherSettings.cpp
Base/ctkAppLauncherSettings.h
Base/ctkAppLauncherSettings_p.h
msvc-static-configure.cmake

User settings file was always stored in the user profile directory, which made it impossible
to create completely self-contained, portable applications (which store all settings within `<APPLAUNCHER_DIR>` and subfolders).
This is addressed by looking for `UserAdditionalSettings` file at `<APPLAUNCHER_DIR>/<organisationName|organizationDomain>/<ApplicationName>(-<revision>).ini`
first and if it is found then that is used. If settings is not found there then the user's profile directory is used the same way as before.
This change is necessary for allowing portable installations of 3D Slicer (https://github.com/Slicer/Slicer/pull/5029).

ENH: Allow user settings file to be in <APPLAUNCHER_DIR>

---

Base/Testing/Cpp/ctkAppLauncherSettingsTest.cpp
Base/Testing/Cpp/ctkAppLauncherTestingHelper.cpp
Base/ctkAppLauncher.cpp
Base/ctkAppLauncherSettings.cpp
Base/ctkAppLauncherSettings.h
Base/ctkAppLauncherSettings_p.h
Testing/LauncherLib/AppWithLauncherLib/launcher-settings.ini
Testing/LauncherLib/AppWithLauncherLib/launcher-user-additional-settings.ini
Testing/LauncherLib/AppWithLauncherLib/main.cpp

This commit is a follow up of 9931394cf (ENH: Allow user settings file
to be in <APPLAUNCHER_DIR> (#114))
See https://github.com/Slicer/Slicer/issues/5437

BUG: Ensure relative paths are resolved when using ctkAppLauncherSettings

---

.circleci/config.yml
.github/workflows/CI.yml
Docs/Doxyfile.txt.in
README.md
appveyor.yml

_Adapted from https://github.com/Slicer/Slicer/pull/6277_
This PR follows recommendations from https://tools.ietf.org/id/draft-knodel-terminology-09.html which have been adopted by many others in the community for work towards the greater good. Although it is often nice to maintain using current terminology, as it relates to improving inclusivity, this should be higher priority.
GitHub has improved the ability to rename a branch (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) which makes it easy to switch to a new name with minimal consequences.
Before merging the following should be done:

Use more inclusive language

---

.github/workflows/CI.yml

Runner "macos-10.15" was removed on 2022.08.30
See https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
> The macos-11 label has been deprecated and will no longer be available
> after 28 June 2024.
Source: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories

COMP: Fix GitHub workflow using current "macos-12" runner

---

appveyor.yml

This commit attempts to address the following errors:
```
pip : DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More
details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
At line:1 char:1
+ pip install scikit-ci-addons==0.18.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (DEPRECATION: Py...ython-2-support:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
[...]
ERROR: Could not find a version that satisfies the requirement backoff~=2.1.2 (from githubrelease>=1.5.6->scikit-ci-addons==0.18.0) (from …
```

COMP: Fix appveyor package upload using "Python38-x64" instead of "Python27-x64"

---

.circleci/config.yml

Update docker image used to install scikit-ci-addons to use `cimg/python:3.10` providing a version of OpenSSL >= 1.1.1
References:
* https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#ssl-module-is-compiled-with-openssl-1-0-2-k-fips
* https://circleci.com/developer/images/image/cimg/python

COMP: Fix setup of CircleCI python env. used to upload package

---

appveyor.yml

Attempt to fix the following error:
```
ci_addons : Traceback (most recent call last):
At line:2 char:1
+ ci_addons publish_github_release commontk/applauncher       `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
File "c:\python38-x64\lib\site-packages\anyci\publish_github_release.py", line 443, in <module>
main()
File "c:\python38-x64\lib\site-packages\anyci\publish_github_release.py", line 436, in main
_upload_prerelease(args)
File "c:\python38-x64\lib\site-packages\anyci\publish_github_release.py", line 309, in _upload_prerelease
gh_release_create(
File "c:\python38-x64\lib\site-packages\github_release.py", line 132, in …
```

COMP: Update Appveyor ensuring latest version of scikit-ci-addons is installed

---

appveyor.yml

Previous value of the corresponding "Personal access token" had been discarded and a new token needed to be generated.

COMP: Update appveyor secure env. value associated with GITHUB_TOKEN

---

.circleci/config.yml
Dockerfile
docker-build-package.sh

This commit is an attempt to fix errors like the following:
```
[...]
Found a cache from build 718 at applauncher-build-934889f29d7d1ea60adf7b6d8844028749872863
Size: 103 MiB
Cached paths:
* /usr/src/AppLauncher-build
Downloading cache archive...
Validating cache...
Download duration for cache file /tmp/cache1192561374: 2.771237192s
Unarchiving cache...
Skipping writing "usr/src/AppLauncher-build/" - mkdir /usr/src/AppLauncher-build: permission denied
Skipping writing "usr/src/AppLauncher-build/Base/" - mkdir /usr/src/AppLauncher-build: permission denied
[...]
/bin/bash: line 6: cd: /usr/src/AppLauncher: No such file or directory
```

COMP: Attempt to fix restoration of cache in upload job

---

.github/scripts/dockbuild_with_qt_env.sh
.github/scripts/dockbuild_xvfb_wrapper.sh
.github/workflows/CI.yml
Base/Testing/Cpp/CMakeLists.txt
Main.cpp
Testing/LauncherLib/CMakeLists.txt
linux-static-configure.cmake
msvc-static-configure.cmake

This adds a `linux-tests` job to the GitHub Actions workflow that builds and tests the project in a self-contained container environment provided by `dockbuild`.
Highlights:
- Uses a statically built Qt 5.15.2 archive downloaded and extracted at runtime.
- Runs the build inside a container (`almalinux8-devtoolset14-gcc14`) launched via a wrapper script.
- Adds `.github/scripts/dockbuild_xvfb_wrapper.sh` to enable running GUI tests via `xvfb-run`, including cleanup logic.

ci: Add Linux test job using dockbuild and Qt static archive 

---

Testing/Launcher/AppLauncher-Param-TestLauncherVersion.cmake
Testing/Launcher/AppLauncher-TestSaveLauncherEnvironment.cmake
Testing/Launcher/AppLauncherTestPrerequisites.cmake.in
Testing/Launcher/CMakeLists.txt
Testing/LauncherLib/CMakeLists.txt

This update addresses a race condition that occurred during parallel test execution (`ctest -jN`), where multiple tests using the same launcher binary would write or read from conflicting files (e.g., `LauncherSettings.ini`), leading to nondeterministic failures.
Test environments are now fully isolated per launcher instance. It prevents `.ini` or log file conflicts and improves reliability in parallel test runs.
* Each test now receives a unique copy of the launcher executable.
* The test name is hashed (`MD5(TEST_NAME)`), and the suffix is appended to the launcher name.
* All references to the launcher within the test environment (`launcher_name`, `launcher`, `launcher_exe`) are updated accordingly.
* Launcher copying is done using `file(COPY_FILE)` (or `configure_file(COPYONLY)` for …

tests: Ensure launcher isolation per test to prevent parallel execution conflicts

---

.github/dependabot.yml
.github/workflows/CI.yml

This pull request improves the CI pipeline introducing these changes:
* Follow GitHub's security hardening recommendations pinning GitHub Actions to Full-Length Commit SHAs
* Add Dependabot Configuration to automate the update of GitHub Actions version.

Improve CI security and add Dependabot configuration

---

Base/Testing/Cpp/ctkAppLauncherEnvironmentTest.cpp
Base/ctkAppArguments.cpp
Base/ctkAppLauncherEnvironment.cpp
Base/ctkCommandLineParser.cpp
Base/ctkCommandLineParser.h
Base/ctkTest.h
Main.cpp

Should fix the issues described here: https://discourse.slicer.org/t/slicer-ignoring-command-line-path-with-accents/24569

Fix passing of non-ASCII characters as command-line arguments

---

.github/workflows/CD.yml
.github/workflows/CI.yml

Introduces a new Continuous Deployment (CD) workflow that automates the publishing of release artifacts. This workflow can be triggered by a published release or manually by specifying a 
Git tag.

ci: Add Continuous  Deployment (CD) workflow

---

.github/workflows/CI.yml

Allow test jobs to be skipped when the 'paths-to-include' filter determined that no relevant files were modified (e.g., only docs or README changed). This ensures the 'pass' job still succeeds and branch protection is satisfied.

ci: Ensure "pass" job succeeds when test jobs are skipped

---

Base/CMakeLists.txt
Base/ctkCommandLineParser.cpp
Base/ctkCommandLineParser.h

Adapted from the following commits:
* commontk/CTK@c8fd5a716 (`Export file header now start with "ctk" lower case`, 2010-10-21)
* commontk/CTK@95da21e40 (`ctkCommandLineParser - Expose property to python using Q_PROPERTY and Q_INVOKABLE`, 2011-01-12)
* commontk/CTK@9935b6ab3 (`Added group definitions and assignments for doxygen.`, 2011-02-10)
* commontk/CTK@6ad270464 (`Fixed doxygen warnings (in user doc).`, 2011-02-15)
* commontk/CTK@a1d82025e (`Add missing license header to Libs/Core files`, 2011-07-09)
* commontk/CTK@0d0ec63a1 (`Use http://www.apache.org/licenses/LICENSE-2.0.txt instead of http://www.commontk.org/LICENSE`, 2011-07-09)
* commontk/CTK@fb10973fa (`Converted CommandLineParser example code to a compilable snippet.`, 2011-12-02)

chore: Backport CTK updates for ctkCommandLineParser class

---

Base/Testing/Cpp/ctkAppArgumentsTest.cpp
Base/Testing/Cpp/ctkAppLauncherEnvironmentTest.cpp
Base/Testing/Cpp/ctkAppLauncherSettingsTest.cpp
Base/Testing/Cpp/ctkAppLauncherTest1.cpp
Base/Testing/Cpp/ctkAppLauncherTestingHelper.cpp
Base/Testing/Cpp/ctkAppLauncherTestingHelper.h
Base/Testing/Cpp/ctkAppLauncherTestingHelper.txx
Base/Testing/Cpp/ctkCommandLineParserTest1.cpp
Base/ctkAppArguments.cpp
Base/ctkAppArguments.h
Base/ctkAppLauncher.cpp
Base/ctkAppLauncher.h
Base/ctkAppLauncherEnvironment.cpp
Base/ctkAppLauncherSettings.cpp
Base/ctkAppLauncherSettings_p.h
Base/ctkCommandLineParser.cpp
Base/ctkSettingsHelper.cpp
Base/ctkTest.h
Main.cpp
Testing/Launcher/App4Test/Main.cpp.in
Testing/Launcher/App4Test/lib.template/app4TestLib.cpp.in
Testing/LauncherLib/AppWithLauncherLib/main.cpp

_Adapted from similar pull request integrated in Slicer, see https://github.com/Slicer/Slicer/pull/7596_
---
This commit reindents the C++ source files to adhere to the "Allman" style, moving away from the outdated and VTK-specific "Whitesmiths" style. The changes are applied using an approach similar to the one utilized in kitware/VTK@f830ff47b3 ("Reindent using the reindentation script," 2016-09-23).
These modifications are made in anticipation of future changes that will introduce the use of a standard configuration based on clang-format.
Once integrated, this commit will be added to the `.git-blame-ignore-revs`[^1] file.
[^1]: https://github.com/Slicer/Slicer/blob/main/.git-blame-ignore-revs
The script `Utilities/Maintenance/vtk_reindent_code.py` is executed, leveraging the approach …

style: Convert C++ source files from old-style "Whitesmiths" to "Allman" style

---

Base/ctkCommandLineParser.cpp

Backport commontk/CTK@5314b9cbb (`BUG: Fixed multi-value argument parsing`, 2017-04-25) integrated into upstream CTK through the following pull request:
* https://github.com/commontk/CTK/pull/710
---
When a multi-value argument was passed to the command-line parser, all subsequent parameters were considered part of the argument.
The root cause of the problem was that the check that compared a parameter to a known argument was incorrect: the parameter name
contained the prefix (--argname) and this string was searched among argument names (such as argname).
Fixed by parsing each parameter after a multi-value argument. If a known argument is found, it is not added to the multi-value argument.

fix(cli): correctly parse multi-value arguments by stopping at next known argument

---

Base/Testing/Cpp/CMakeLists.txt
CMake/ctkMacroBuildLib.cmake
CMakeLists.txt
README.md
Testing/CMakeLists.txt
Testing/LauncherLib/AppWithLauncherLib-ConfigureStep.cmake
Testing/LauncherLib/CMakeLists.txt

All references to Qt4 have been removed and attempts to set CTKAppLauncher_QT_VERSION to '4' will now result in a fatal error.
Note that to support launching Qt4-based applications, the `ArgumentToFilterList` in `appLauncherMain` in `Main.cpp`[^1] still lists Qt4 specific arguments.
[^1]: https://github.com/commontk/AppLauncher/blob/v0.1.32/Main.cpp#L35-L73

COMP: Remove support for building against Qt4

---

.github/workflows/CI.yml

The macOS 13 runner will be retired by December 4th, 2025 with scheduled brownout periods in November. See https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
> [!NOTE]
> [Successful testing run](https://github.com/commontk/AppLauncher/actions/runs/17916685791/job/50940625884) ran on macos-14-arm64. If an Intel variant needs to be used, then `macos-15-intel` will have to be specified.

ci: Upgrade to "macos-14" runner
